name: Flutter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.7.0

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze
        
      - name: Format check
        run: dart format lib --set-exit-if-changed --dry-run
